name: Cyberacademy test CI

on:  
  pull_request:
    branches:
      - main

jobs:  
  task-01:
    name: CyberAcademy Task 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Perintah Linux
        run: |
          git status
          ls -lah
          id
          echo "Me is here"
